export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"
export const USER_REGISTER_RESET = "USER_REGISTER_RESET"

export const USER_UPDATE_ACCOUNT_REQUEST = "USER_UPDATE_ACCOUNT_REQUEST"
export const USER_UPDATE_ACCOUNT_SUCCESS = "USER_UPDATE_ACCOUNT_SUCCESS"
export const USER_UPDATE_ACCOUNT_FAIL = "USER_UPDATE_ACCOUNT_FAIL"
export const USER_UPDATE_ACCOUNT_RESET = "USER_UPDATE_ACCOUNT_RESET"

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST"
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS"
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL"
export const USER_RESET_PASSWORD_RESET = "USER_RESET_PASSWORD_RESET"

export const USER_NEW_PASSWORD_REQUEST = "USER_NEW_PASSWORD_REQUEST"
export const USER_NEW_PASSWORD_SUCCESS = "USER_NEW_PASSWORD_SUCCESS"
export const USER_NEW_PASSWORD_FAIL = "USER_NEW_PASSWORD_FAIL"
export const USER_NEW_PASSWORD_RESET = "USER_NEW_PASSWORD_RESET"

export const USER_VERIFY_ACCOUNT_REQUEST = "USER_VERIFY_ACCOUNT_REQUEST"
export const USER_VERIFY_ACCOUNT_SUCCESS = "USER_VERIFY_ACCOUNT_SUCCESS"
export const USER_VERIFY_ACCOUNT_FAIL = "USER_VERIFY_ACCOUNT_FAIL"
export const USER_VERIFY_ACCOUNT_RESET = "USER_VERIFY_ACCOUNT_RESET"